apiVersion: apps/v1
kind: Deployment
metadata:
  name: viewer
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viewer
  template:
    metadata:
      labels:
        app: viewer
    spec:
      containers:
      - name: viewer
        imagePullPolicy: Always
        image: opentechxdoclabs/smart_hr_system:resume-viewer-arm64-new
        env:
        - name: AWS_S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: AWS_S3_BUCKET_NAME
        - name: AWS_REGION_NAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: AWS_REGION_NAME
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_DB
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_PASSWORD
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_PORT
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: MYSQL_USER
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: credentials
              key: OPENAI_API_KEY
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: credentials
              key: AWS_SECRET_ACCESS_KEY

        ports:
        - containerPort: 8004
      imagePullSecrets:
      - name: docker-registry-secret
